
import { AgentProduct, AgentCategory, LicenseTier, Review } from './types';

const STANDARD_FILES = [
  { name: 'spec.md', type: 'md', description: 'Core requirements & success metrics' },
  { name: 'profile.md', type: 'md', description: 'Persona, voice & world-view' },
  { name: 'capabilities.md', type: 'md', description: 'Functional breakdown' },
  { name: 'workflow.yml', type: 'yml', description: 'Logic flow & state definitions' },
  { name: 'logic.pseudo', type: 'pseudo', description: 'Algorithmic reasoning pseudo-code' },
  { name: 'tools.json', type: 'json', description: 'Function calling definitions' },
  { name: 'instructions/gemini.txt', type: 'txt', description: 'Gemini System Prompt' },
  { name: 'instructions/claude.txt', type: 'txt', description: 'Claude System Prompt' },
];

export const agents: AgentProduct[] = [
  // --- Bundles (New) ---
  {
    id: 'bundle-1',
    name: 'Startup Founders Pack',
    role: 'Executive Suite',
    category: AgentCategory.BUNDLE,
    price: 299, // Discounted price vs buying separately (199 + 149 = 348)
    description: 'The ultimate leadership combo. Contains the CEO Advisor and Product Visionary agents to kickstart your venture with perfect strategic alignment.',
    features: ['Includes CEO Advisor', 'Includes Product Visionary', 'Unified Strategy Protocol', '15% Bundle Discount'],
    compatiblePlatforms: ['Gemini', 'Claude'],
    filesIncluded: [
      { name: 'master-manifest.json', type: 'json', description: 'Bundle Orchestration Map' },
      ...STANDARD_FILES
    ] as any,
    popularity: 99,
    downloads: 2100,
    rating: 5.0,
    ratingCount: 210,
    isTrending: true,
    licenseTier: LicenseTier.ENTERPRISE,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 },
    isBundle: true,
    containedAgentIds: ['strat-1', 'strat-2'] // CEO and Product Visionary
  },

  // --- Strategic ---
  {
    id: 'strat-1',
    name: 'CEO Advisor / Orchestrator',
    role: 'Orchestration Engine',
    category: AgentCategory.STRATEGIC,
    price: 199,
    description: 'The central nervous system of your AI workforce. Delegates tasks, oversees project timelines, and ensures strategic alignment across all other agents.',
    features: ['Project Leadership', 'Task Delegation', 'Conflict Resolution', 'Strategic Planning'],
    compatiblePlatforms: ['Gemini', 'ChatGPT', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 98,
    downloads: 1240,
    rating: 5.0,
    ratingCount: 124,
    isNew: true,
    isTrending: true,
    licenseTier: LicenseTier.ENTERPRISE,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },
  {
    id: 'strat-2',
    name: 'Product Visionary',
    role: 'Senior Product Manager',
    category: AgentCategory.STRATEGIC,
    price: 149,
    description: 'Transforms abstract ideas into concrete PRDs. Focuses on user value, market fit, and feature prioritization based on the OpenOps framework.',
    features: ['PRD Generation', 'User Journey Mapping', 'Feature Prioritization'],
    compatiblePlatforms: ['Gemini', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 92,
    downloads: 890,
    rating: 4.8,
    ratingCount: 89,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },
  {
    id: 'strat-3',
    name: 'Venture Strategist',
    role: 'Finance & Strategy',
    category: AgentCategory.STRATEGIC,
    price: 149,
    description: 'Analyzes business models, financial runways, and investment opportunities. Optimized for scaling startups.',
    features: ['Financial Modeling', 'Pitch Deck Review', 'Market Sizing'],
    compatiblePlatforms: ['ChatGPT', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 85,
    downloads: 560,
    rating: 4.7,
    ratingCount: 56,
    licenseTier: LicenseTier.COMMERCIAL,
    vendor: { id: 'v2', name: 'VentureAI', verified: false, rating: 4.5 }
  },
  {
    id: 'strat-4',
    name: 'Cultural Consultant',
    role: 'Culture & Operations',
    category: AgentCategory.STRATEGIC,
    price: 129,
    description: 'Ensures organizational culture aligns with growth goals, with specific modules for MENA workplace dynamics.',
    features: ['Culture Audit', 'Team Dynamics', 'Remote Work Policy'],
    compatiblePlatforms: ['Gemini', 'ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 70,
    downloads: 320,
    rating: 4.5,
    ratingCount: 32,
    licenseTier: LicenseTier.PERSONAL,
    vendor: { id: 'v3', name: 'CultureFlow', verified: true, rating: 4.2 }
  },
  {
    id: 'strat-5',
    name: 'Innovation Scout',
    role: 'Tech Futurist',
    category: AgentCategory.STRATEGIC,
    price: 139,
    description: 'Scans the horizon for emerging technologies (AI, Web3, Biotech) relevant to your specific product roadmap.',
    features: ['Trend Analysis', 'Competitor Tech Watch', 'R&D Suggestions'],
    compatiblePlatforms: ['Gemini', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 88,
    downloads: 670,
    rating: 4.9,
    ratingCount: 67,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v4', name: 'FutureSight', verified: true, rating: 4.8 }
  },

  // --- Engineering ---
  {
    id: 'eng-1',
    name: 'Architectural Integrity',
    role: 'Staff Engineer',
    category: AgentCategory.ENGINEERING,
    price: 179,
    description: 'Guardian of system integrity. Reviews code structure, enforces patterns, and prevents technical debt before it happens.',
    features: ['Code Review', 'System Design', 'Debt Prevention'],
    compatiblePlatforms: ['Claude', 'ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 95,
    downloads: 1560,
    rating: 5.0,
    ratingCount: 156,
    isTrending: true,
    licenseTier: LicenseTier.ENTERPRISE,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },
  {
    id: 'eng-2',
    name: 'Design System Agent',
    role: 'UX/UI Engineer',
    category: AgentCategory.ENGINEERING,
    price: 149,
    description: 'Enforces frontend standards, Tailwind utility usage, and accessibility compliance across your React components.',
    features: ['Component Audit', 'Tailwind Optimization', 'Accessibility Check'],
    compatiblePlatforms: ['Gemini', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 90,
    downloads: 1120,
    rating: 4.8,
    ratingCount: 112,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v5', name: 'PixelPerfect', verified: false, rating: 4.6 }
  },
  {
    id: 'eng-3',
    name: 'Performance Auditor',
    role: 'Performance Engineer',
    category: AgentCategory.ENGINEERING,
    price: 129,
    description: 'Analyzes application bundles, render cycles, and API latency to suggest concrete optimizations.',
    features: ['Bundle Analysis', 'React Render Audit', 'Web Vitals'],
    compatiblePlatforms: ['ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 80,
    downloads: 480,
    rating: 4.6,
    ratingCount: 48,
    licenseTier: LicenseTier.PERSONAL,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },
  {
    id: 'eng-4',
    name: 'Security Architect',
    role: 'Security Auditor',
    category: AgentCategory.ENGINEERING,
    price: 199,
    description: 'Specialized in OWASP Top 10 prevention, dependency scanning, and secure coding practices for Node/React apps.',
    features: ['Vulnerability Scan', 'Auth Flow Review', 'Data Privacy'],
    compatiblePlatforms: ['Claude', 'Gemini'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 94,
    downloads: 1430,
    rating: 4.9,
    ratingCount: 143,
    licenseTier: LicenseTier.ENTERPRISE,
    vendor: { id: 'v6', name: 'SecurOps', verified: true, rating: 5.0 }
  },
  {
    id: 'eng-5',
    name: 'DevOps Automator',
    role: 'Automation Engineer',
    category: AgentCategory.ENGINEERING,
    price: 159,
    description: 'Writes CI/CD pipelines, Dockerfiles, and Terraform scripts. Automates the boring stuff.',
    features: ['CI/CD Config', 'Infrastructure as Code', 'Scripting'],
    compatiblePlatforms: ['ChatGPT', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 89,
    downloads: 980,
    rating: 4.7,
    ratingCount: 98,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v7', name: 'CloudNative', verified: true, rating: 4.7 }
  },

  // --- Creative ---
  {
    id: 'creat-1',
    name: 'Egyptian Dialect Writer',
    role: 'Localized Content',
    category: AgentCategory.CREATIVE,
    price: 99,
    description: 'Master of "Masri" copy. Writes engaging, culturally resonant social media posts and ads for the Egyptian market.',
    features: ['Social Media Copy', 'Slang Adaptation', 'Humor Injection'],
    compatiblePlatforms: ['Gemini', 'ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 96,
    downloads: 2870,
    rating: 5.0,
    ratingCount: 287,
    isNew: true,
    licenseTier: LicenseTier.PERSONAL,
    vendor: { id: 'v8', name: 'MasriAI', verified: true, rating: 4.9 }
  },
  {
    id: 'creat-2',
    name: 'Conversion Copywriter',
    role: 'PPC Specialist',
    category: AgentCategory.CREATIVE,
    price: 119,
    description: 'Writes high-converting ad copy for Google Ads, Meta, and LinkedIn based on behavioral psychology.',
    features: ['Ad Copy', 'Landing Page Headlines', 'A/B Test Ideas'],
    compatiblePlatforms: ['Claude', 'ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 88,
    downloads: 1340,
    rating: 4.8,
    ratingCount: 134,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v9', name: 'AdBot', verified: false, rating: 4.5 }
  },
  {
    id: 'creat-3',
    name: 'Content Distributor',
    role: 'Growth Hacker',
    category: AgentCategory.CREATIVE,
    price: 109,
    description: 'Repurposes one core piece of content into tweets, LinkedIn posts, blog summaries, and newsletters.',
    features: ['Repurposing', 'Viral Hooks', 'Platform Formatting'],
    compatiblePlatforms: ['Gemini'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 82,
    downloads: 760,
    rating: 4.6,
    ratingCount: 76,
    licenseTier: LicenseTier.PERSONAL,
    vendor: { id: 'v10', name: 'ViralLoops', verified: true, rating: 4.3 }
  },
  {
    id: 'creat-4',
    name: 'AEO Specialist',
    role: 'AI SEO Expert',
    category: AgentCategory.CREATIVE,
    price: 149,
    description: 'Optimizes content not just for Google Search, but for AI Answer Engines (Perplexity, SearchGPT, Gemini).',
    features: ['Fact structuring', 'Snippet Optimization', 'Authority Building'],
    compatiblePlatforms: ['Claude', 'Gemini'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 91,
    downloads: 1150,
    rating: 4.9,
    ratingCount: 115,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },
  {
    id: 'creat-5',
    name: 'Growth Loop Engineer',
    role: 'Growth Marketer',
    category: AgentCategory.CREATIVE,
    price: 159,
    description: 'Designs viral loops and referral programs. Analyzes funnel drop-offs to plug leaks.',
    features: ['Funnel Analysis', 'Referral Mechanics', 'Retention Strategy'],
    compatiblePlatforms: ['ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 87,
    downloads: 630,
    rating: 4.7,
    ratingCount: 63,
    licenseTier: LicenseTier.COMMERCIAL,
    vendor: { id: 'v10', name: 'ViralLoops', verified: true, rating: 4.3 }
  },

  // --- Regional ---
  {
    id: 'reg-1',
    name: 'Saudi Market Analyst',
    role: 'Regional Strategy',
    category: AgentCategory.REGIONAL,
    price: 169,
    description: 'Deep knowledge of Vision 2030, Saudi consumer behavior, and regulatory landscape.',
    features: ['Vision 2030 Alignment', 'Consumer Trends', 'Localization'],
    compatiblePlatforms: ['Gemini', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 93,
    downloads: 1920,
    rating: 4.9,
    ratingCount: 192,
    licenseTier: LicenseTier.ENTERPRISE,
    vendor: { id: 'v11', name: 'KhaleejTech', verified: true, rating: 4.8 }
  },
  {
    id: 'reg-2',
    name: 'Levantine Localizer',
    role: 'Content Localization',
    category: AgentCategory.REGIONAL,
    price: 99,
    description: 'Specializes in Jordanian, Lebanese, and Syrian dialects for natural-sounding customer support and content.',
    features: ['Dialect Translation', 'Tone Adjustment', 'Cultural Nuance'],
    compatiblePlatforms: ['ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 75,
    downloads: 420,
    rating: 4.6,
    ratingCount: 42,
    licenseTier: LicenseTier.PERSONAL,
    vendor: { id: 'v12', name: 'LevantAI', verified: false, rating: 4.4 }
  },
  {
    id: 'reg-3',
    name: 'GCC Business Liaison',
    role: 'Partnerships',
    category: AgentCategory.REGIONAL,
    price: 139,
    description: 'Expert in formal business Arabic (Fusha) and GCC business etiquette for emails and proposals.',
    features: ['Formal Correspondence', 'Proposal Writing', 'Etiquette Check'],
    compatiblePlatforms: ['Claude', 'Gemini'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 81,
    downloads: 580,
    rating: 4.7,
    ratingCount: 58,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v11', name: 'KhaleejTech', verified: true, rating: 4.8 }
  },
  {
    id: 'reg-4',
    name: 'Halal Compliance',
    role: 'Risk & Ethics',
    category: AgentCategory.REGIONAL,
    price: 119,
    description: 'Ensures marketing, finance products, and operations adhere to Islamic ethical standards.',
    features: ['Sharia Compliance Check', 'Ethical Marketing', 'Fintech Audit'],
    compatiblePlatforms: ['Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 78,
    downloads: 890,
    rating: 5.0,
    ratingCount: 89,
    licenseTier: LicenseTier.COMMERCIAL,
    vendor: { id: 'v13', name: 'EthicAI', verified: true, rating: 5.0 }
  },
  {
    id: 'reg-5',
    name: 'Regional Pricing',
    role: 'Economics',
    category: AgentCategory.REGIONAL,
    price: 129,
    description: 'Adjusts pricing models based on purchasing power parity (PPP) across different MENA countries.',
    features: ['PPP Analysis', 'Competitor Pricing', 'Currency Risk'],
    compatiblePlatforms: ['ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 76,
    downloads: 280,
    rating: 4.5,
    ratingCount: 28,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },

  // --- Operations ---
  {
    id: 'ops-1',
    name: 'Accessibility Enforcer',
    role: 'Compliance',
    category: AgentCategory.OPERATIONS,
    price: 109,
    description: 'Ensures WCAG 2.1 compliance for digital products. Acts as a strict auditor.',
    features: ['WCAG Audit', 'Screen Reader Simulation', 'Color Contrast'],
    compatiblePlatforms: ['Gemini'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 84,
    downloads: 770,
    rating: 4.8,
    ratingCount: 77,
    licenseTier: LicenseTier.PERSONAL,
    vendor: { id: 'v14', name: 'A11yBot', verified: false, rating: 4.6 }
  },
  {
    id: 'ops-2',
    name: 'Doc Custodian',
    role: 'Documentation',
    category: AgentCategory.OPERATIONS,
    price: 89,
    description: 'Maintains, updates, and organizes internal wikis and API documentation. Hates stale docs.',
    features: ['Doc Generation', 'Change Log Management', 'Knowledge Base'],
    compatiblePlatforms: ['Claude', 'ChatGPT'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 80,
    downloads: 540,
    rating: 4.6,
    ratingCount: 54,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v1', name: 'OpenOps Core', verified: true, rating: 4.9 }
  },
  {
    id: 'ops-3',
    name: 'Compliance / Legal',
    role: 'Risk',
    category: AgentCategory.OPERATIONS,
    price: 189,
    description: 'Drafts Terms of Service, Privacy Policies, and reviews contracts for standard clauses.',
    features: ['Contract Review', 'TOS Generation', 'Risk Flagging'],
    compatiblePlatforms: ['Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 86,
    downloads: 910,
    rating: 4.7,
    ratingCount: 91,
    licenseTier: LicenseTier.COMMERCIAL,
    vendor: { id: 'v15', name: 'LegalTech', verified: true, rating: 4.8 }
  },
  {
    id: 'ops-4',
    name: 'Data Privacy (NDMO)',
    role: 'Compliance',
    category: AgentCategory.OPERATIONS,
    price: 199,
    description: 'Specialized in Saudi NDMO data classification and privacy standards.',
    features: ['NDMO Classification', 'Data Flow Mapping', 'Privacy Audit'],
    compatiblePlatforms: ['Gemini', 'Claude'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 89,
    downloads: 350,
    rating: 5.0,
    ratingCount: 35,
    isNew: true,
    licenseTier: LicenseTier.ENTERPRISE,
    vendor: { id: 'v11', name: 'KhaleejTech', verified: true, rating: 4.8 }
  },
  {
    id: 'ops-5',
    name: 'Support Loop Agent',
    role: 'Customer Success',
    category: AgentCategory.OPERATIONS,
    price: 119,
    description: 'Analyzes support tickets to identify product bugs and feature requests. Closes the loop with product teams.',
    features: ['Ticket Analysis', 'Sentiment Analysis', 'Feature Extraction'],
    compatiblePlatforms: ['ChatGPT', 'Gemini'],
    filesIncluded: STANDARD_FILES as any,
    popularity: 91,
    downloads: 1210,
    rating: 4.9,
    ratingCount: 121,
    licenseTier: LicenseTier.TEAM,
    vendor: { id: 'v16', name: 'SupportAI', verified: true, rating: 4.7 }
  }
];

const MOCK_REVIEWS: Review[] = [
  { id: 'r1', author: 'Sarah Jenkins', role: 'Product Lead', rating: 5, comment: 'The structural integrity of this agent is incredible. It handles edge cases I hadn\'t even thought of.', date: '2 days ago' },
  { id: 'r2', author: 'Ahmed Al-Sayed', role: 'Tech Founder', rating: 5, comment: 'Finally, high-quality Arabic support. The dialect nuances are spot on.', date: '1 week ago' },
  { id: 'r3', author: 'Mike Chen', role: 'DevOps Engineer', rating: 4, comment: 'Great documentation. Setup took less than 5 minutes on Claude.', date: '3 weeks ago' },
  { id: 'r4', author: 'Elena Rodriguez', role: 'Marketing Director', rating: 5, comment: 'The creative output from this agent doubled our engagement rates.', date: '1 month ago' },
  { id: 'r5', author: 'David Kim', role: 'Solutions Architect', rating: 4, comment: 'Very robust JSON definitions. Would appreciate more TypeScript examples in the docs.', date: '2 months ago' }
];

export const getReviewsForAgent = (agentId: string): Review[] => {
  // Deterministic pseudo-random selection based on ID length
  const count = (agentId.length % 3) + 2; 
  return MOCK_REVIEWS.slice(0, count);
};

export const getSimilarAgents = (currentAgent: AgentProduct): AgentProduct[] => {
  return agents
    .filter(a => a.category === currentAgent.category && a.id !== currentAgent.id)
    .sort((a, b) => b.popularity - a.popularity) // Show most popular similar ones
    .slice(0, 3);
};