import type { MarketplaceAgent } from "./types";

export const marketplaceAgents: MarketplaceAgent[] = [
  {
    id: "paid-media-plan-architect",
    order: "01",
    name: "Paid Media Plan Architect",
    category: "Paid Media",
    description:
      "Builds clear media plans with numbers, audience logic, channel mix, messaging, budget split, and testing priorities.",
    priceEgp: 2999,
    freeLabel: "Free For limited Time",
    bestFor: "Media buyers, performance teams, and account teams preparing launch plans.",
    promise: "A campaign plan the team can understand, approve, and execute without long back-and-forth.",
    deliverables: [
      "Campaign objective and KPI map",
      "Audience segments and funnel stages",
      "Channel and budget allocation",
      "Message angles and creative testing matrix",
    ],
    inputs: ["Offer", "target market", "budget", "platforms", "timeline", "past results"],
    workflow: ["Brief intake", "funnel mapping", "media mix", "budget logic", "launch checklist"],
    installCommand: "claude plugin install openops/paid-media-plan-architect",
  },
  {
    id: "ugc-script-writer",
    order: "02",
    name: "UGC & Script Writer",
    category: "Creative",
    description:
      "Writes UGC hooks, scripts, creator directions, ad concepts, and social video angles that creators can shoot.",
    priceEgp: 1790,
    freeLabel: "Free For limited Time",
    bestFor: "Content teams, media buyers, and creator managers working on short-form video.",
    promise: "Creator-ready scripts with hook logic, scene notes, proof points, and CTA options.",
    deliverables: ["Hook bank", "UGC scripts", "creator brief", "shot direction"],
    inputs: ["Product", "audience", "pain points", "proof", "platform", "desired tone"],
    workflow: ["Angle discovery", "hook writing", "script drafting", "creator notes", "variant export"],
    installCommand: "claude plugin install openops/ugc-script-writer",
  },
  {
    id: "creative-strategist",
    order: "03",
    name: "Creative Strategist",
    category: "Creative",
    description:
      "Develops campaign ideas, content angles, creative territories, and testing directions the team can turn into published work.",
    priceEgp: 3900,
    freeLabel: "Free For limited Time",
    bestFor: "Creative, social, and paid teams that need sharper concepts before production.",
    promise: "A practical creative strategy with angles, hypotheses, references, and testable executions.",
    deliverables: ["Creative territories", "campaign angles", "ad hypotheses", "execution notes"],
    inputs: ["Brand", "objective", "audience", "offer", "constraints", "competitors"],
    workflow: ["Context scan", "angle mapping", "idea shaping", "test plan", "production brief"],
    installCommand: "claude plugin install openops/creative-strategist",
  },
  {
    id: "gtm-sales-consultant",
    order: "04",
    name: "GTM / Sales Consultant",
    category: "Growth",
    description:
      "Shapes go-to-market offers, lead generation logic, sales messages, and offer clarity before campaigns go live.",
    priceEgp: 7400,
    freeLabel: "Free For limited Time",
    bestFor: "Founders, sales teams, and agencies preparing market entry or new offer launches.",
    promise: "A clearer offer, sharper buyer path, and a more coherent sales narrative.",
    deliverables: ["GTM outline", "lead gen path", "sales messages", "offer diagnosis"],
    inputs: ["Product", "market", "buyer", "price", "sales motion", "current objections"],
    workflow: ["Offer audit", "buyer journey", "lead logic", "message stack", "launch notes"],
    installCommand: "claude plugin install openops/gtm-sales-consultant",
  },
  {
    id: "social-media-specialist",
    order: "05",
    name: "Social Media Specialist",
    category: "Social",
    description:
      "Turns daily ideas into posts, content calendars, caption drafts, and social publishing plans.",
    priceEgp: 699,
    freeLabel: "Free For limited Time",
    bestFor: "Social media teams, creators, and small businesses that need consistent content output.",
    promise: "A practical calendar with post ideas, copy directions, and publishing rhythm.",
    deliverables: ["Content calendar", "post copy", "idea bank", "daily publishing prompts"],
    inputs: ["Brand voice", "topics", "platforms", "posting frequency", "offers", "events"],
    workflow: ["Topic clustering", "calendar planning", "copy drafting", "format selection", "review notes"],
    installCommand: "claude plugin install openops/social-media-specialist",
  },
  {
    id: "seo-aeo-geo-superhero",
    order: "06",
    name: "SEO / AEO / GEO Superhero",
    category: "Search",
    description:
      "Improves search visibility, landing pages, articles, and appearance inside AI-generated answers.",
    priceEgp: 10999,
    freeLabel: "Free For limited Time",
    bestFor: "Content, growth, and SaaS teams that need search-ready pages and answer-first content.",
    promise: "A search visibility plan built around intent, structure, entities, snippets, and AI answer readiness.",
    deliverables: ["Keyword and entity map", "page outline", "answer-first sections", "internal linking notes"],
    inputs: ["Website", "topic", "target market", "competitors", "existing pages", "priority queries"],
    workflow: ["Intent mapping", "content structure", "entity coverage", "snippet design", "QA checklist"],
    installCommand: "claude plugin install openops/seo-aeo-geo-superhero",
  },
  {
    id: "proposals-specialist",
    order: "07",
    name: "Proposals Specialist",
    category: "Proposal",
    description:
      "Builds technical and financial proposals by structuring the requirement, solution, scope, and commercial story.",
    priceEgp: 5999,
    freeLabel: "Free For limited Time",
    bestFor: "Agency teams responding to RFPs, briefs, and procurement requests.",
    promise: "A proposal structure that is easier to approve, price, design, and defend.",
    deliverables: ["Proposal outline", "scope structure", "solution narrative", "pricing logic"],
    inputs: ["RFP", "client brief", "services", "timeline", "team capacity", "pricing assumptions"],
    workflow: ["Requirement sorting", "solution framing", "scope building", "pricing notes", "submission checklist"],
    installCommand: "claude plugin install openops/proposals-specialist",
  },
  {
    id: "saudi-marketer-content-creator",
    order: "08",
    name: "Saudi Marketer / Content Creator",
    category: "Saudi Market",
    description:
      "Adapts marketing and content work for Saudi language, local context, public sector tone, and commercial communication.",
    priceEgp: 12999,
    freeLabel: "Free For limited Time",
    bestFor: "Teams working with Saudi brands, government entities, events, and B2B communication.",
    promise: "Saudi-aware content that respects context, tone, audience expectations, and business etiquette.",
    deliverables: ["Saudi tone rewrite", "local content angles", "campaign lines", "stakeholder messages"],
    inputs: ["Audience", "entity type", "sector", "message", "platform", "formality level"],
    workflow: ["Context check", "tone selection", "message rewrite", "local fit review", "final polish"],
    installCommand: "claude plugin install openops/saudi-marketer-content-creator",
  },
  {
    id: "pr-crisis-expert",
    order: "09",
    name: "PR & Crisis Expert",
    category: "PR",
    description:
      "Creates press materials, official statements, reputation notes, and calm response drafts for sensitive situations.",
    priceEgp: 4999,
    freeLabel: "Free For limited Time",
    bestFor: "PR teams, leadership offices, and agencies dealing with public communication.",
    promise: "Measured communication that reduces confusion, protects trust, and keeps wording controlled.",
    deliverables: ["Press release", "holding statement", "Q&A sheet", "response matrix"],
    inputs: ["Situation", "stakeholders", "risk level", "approved facts", "channels", "spokesperson"],
    workflow: ["Risk scan", "fact sorting", "message hierarchy", "drafting", "approval notes"],
    installCommand: "claude plugin install openops/pr-crisis-expert",
  },
  {
    id: "account-manager",
    order: "10",
    name: "Account Manager",
    category: "Account Management",
    description:
      "Writes client updates, meeting minutes, decision summaries, follow-up notes, and clear status messages.",
    priceEgp: 5999,
    freeLabel: "Free For limited Time",
    bestFor: "Account teams that need cleaner client communication and fewer missed follow-ups.",
    promise: "A clearer client communication layer with next steps, owners, timelines, and decisions.",
    deliverables: ["Client update", "meeting minutes", "action list", "follow-up message"],
    inputs: ["Meeting notes", "client ask", "current status", "pending items", "owners", "deadlines"],
    workflow: ["Note cleanup", "decision extraction", "task mapping", "message drafting", "follow-up plan"],
    installCommand: "claude plugin install openops/account-manager",
  },
  {
    id: "pitch-deck-architect",
    order: "11",
    name: "Pitch Deck Architect",
    category: "Proposal",
    description:
      "Structures sales decks, pitch decks, RFP responses, and commercial stories visually and logically.",
    priceEgp: 1999,
    freeLabel: "Free For limited Time",
    bestFor: "Sales, strategy, and agency teams preparing presentations for decision makers.",
    promise: "A deck narrative that moves from problem to logic to offer to proof to action.",
    deliverables: ["Deck storyline", "slide-by-slide outline", "talk track", "visual notes"],
    inputs: ["Audience", "objective", "offer", "proof points", "duration", "decision criteria"],
    workflow: ["Audience logic", "story spine", "slide sequencing", "proof placement", "closing frame"],
    installCommand: "claude plugin install openops/pitch-deck-architect",
  },
  {
    id: "performance-analyst",
    order: "12",
    name: "Performance Analyst",
    category: "Analytics",
    description:
      "Reads numbers, extracts insights, prepares reports, and turns data into understandable decisions for teams and clients.",
    priceEgp: 2479,
    freeLabel: "Free For limited Time",
    bestFor: "Performance marketers, account managers, and leadership teams reviewing campaign results.",
    promise: "A report that explains what happened, why it matters, and what should happen next.",
    deliverables: ["Performance summary", "insight list", "decision notes", "next-action plan"],
    inputs: ["Campaign data", "period", "targets", "platform notes", "spend", "conversion events"],
    workflow: ["Data sanity check", "KPI reading", "pattern extraction", "insight writing", "action planning"],
    installCommand: "claude plugin install openops/performance-analyst",
  },
];

export const marketplaceStats = [
  { label: "Agents", value: "12" },
  { label: "Current price", value: "Free" },
  { label: "Original value", value: "60,263 EGP" },
  { label: "Primary fit", value: "Marketing teams" },
] as const;
