import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Coverage Map Renderer - Creates heatmap of code coverage
 * Shows which files are covered by which scenarios
 */
export async function renderCoverageMap(scenarios: any[]): Promise<void> {
  console.log('🗺️  Rendering coverage heatmap...');

  const reportsDir = join(process.cwd(), '.test-kit', 'reports');
  mkdirSync(reportsDir, { recursive: true });

  // Build coverage matrix
  const fileSet = new Set<string>();
  for (const scenario of scenarios) {
    scenario.relatedFiles?.forEach((f: string) => fileSet.add(f));
  }

  const files = Array.from(fileSet);
  const coverageMatrix = files.map((file) => {
    const coverageCount = scenarios.filter((s: any) => s.relatedFiles?.includes(file)).length;
    return {
      file,
      coverage: coverageCount,
      testTypes: scenarios
        .filter((s: any) => s.relatedFiles?.includes(file))
        .map((s: any) => s.testType),
    };
  });

  // Create HTML heatmap
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test-Kit Coverage Heatmap</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 20px;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      padding: 30px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
    }
    h1 {
      color: #333;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .subtitle {
      color: #666;
      margin-bottom: 30px;
      font-size: 14px;
    }
    .stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 15px;
      margin-bottom: 30px;
    }
    .stat-card {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 15px;
      border-radius: 8px;
      text-align: center;
    }
    .stat-value {
      font-size: 24px;
      font-weight: bold;
    }
    .stat-label {
      font-size: 12px;
      opacity: 0.9;
    }
    .heatmap {
      border-collapse: collapse;
      width: 100%;
      margin-top: 20px;
    }
    .heatmap th, .heatmap td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #eee;
    }
    .heatmap th {
      background: #f5f5f5;
      font-weight: 600;
      color: #333;
    }
    .heatmap tr:hover {
      background: #f9f9f9;
    }
    .coverage-bar {
      height: 8px;
      background: #e0e0e0;
      border-radius: 4px;
      overflow: hidden;
      width: 100px;
    }
    .coverage-fill {
      height: 100%;
      background: linear-gradient(90deg, #667eea, #764ba2);
      transition: width 0.3s ease;
    }
    .coverage-0 { background: #ff6b6b; }
    .coverage-1 { background: #ffa726; }
    .coverage-2 { background: #ffee58; }
    .coverage-3 { background: #66bb6a; }
    .coverage-high { background: #2e7d32; }
    .test-badges {
      display: flex;
      gap: 5px;
      flex-wrap: wrap;
    }
    .badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 600;
    }
    .badge-unit { background: #e3f2fd; color: #1976d2; }
    .badge-integration { background: #f3e5f5; color: #7b1fa2; }
    .badge-e2e { background: #e8f5e9; color: #388e3c; }
    .badge-eval { background: #fff3e0; color: #f57c00; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🗺️  Test Coverage Heatmap</h1>
    <div class="subtitle">Generated by Test-Kit AI Scenario Designer</div>
    
    <div class="stats">
      <div class="stat-card">
        <div class="stat-value">${files.length}</div>
        <div class="stat-label">Files Analyzed</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${scenarios.length}</div>
        <div class="stat-label">Scenarios</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${(coverageMatrix.reduce((s, c) => s + c.coverage, 0) / (files.length || 1)).toFixed(1)}</div>
        <div class="stat-label">Avg Coverage</div>
      </div>
    </div>

    <table class="heatmap">
      <thead>
        <tr>
          <th>File</th>
          <th>Coverage</th>
          <th>Test Types</th>
        </tr>
      </thead>
      <tbody>
        ${coverageMatrix
          .sort((a, b) => b.coverage - a.coverage)
          .map(
            (item) => `
        <tr>
          <td style="font-family: monospace; font-size: 12px;">${item.file}</td>
          <td>
            <div style="display: flex; align-items: center; gap: 8px;">
              <div class="coverage-bar">
                <div class="coverage-fill" style="width: ${(item.coverage / 5) * 100}%"></div>
              </div>
              <span class="coverage-${item.coverage} badge" style="padding: 4px 8px; border-radius: 4px; font-size: 12px;">${item.coverage}</span>
            </div>
          </td>
          <td>
            <div class="test-badges">
              ${item.testTypes
                .map(
                  (type) =>
                    `<span class="badge badge-${type}">${type.toUpperCase()}</span>`
                )
                .join('')}
            </div>
          </td>
        </tr>
          `
          )
          .join('')}
      </tbody>
    </table>
  </div>
</body>
</html>`;

  writeFileSync(join(reportsDir, 'coverage-heatmap.html'), htmlContent);
  console.log('🔥 Coverage heatmap rendered → .test-kit/reports/coverage-heatmap.html');
}
