import { Scenario } from '../ai';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Scenario Tree Renderer - Creates Mermaid diagrams of test scenarios
 * Visualizes relationships between scenarios and components
 */
export async function renderScenarioTree(scenarios: Scenario[]): Promise<string> {
  console.log('🎨 Rendering scenario tree diagram...');

  const mermaidLines: string[] = ['graph TD'];

  // Group scenarios by type
  const byType = new Map<string, Scenario[]>();
  for (const scenario of scenarios) {
    const type = scenario.testType;
    if (!byType.has(type)) byType.set(type, []);
    byType.get(type)!.push(scenario);
  }

  // Create nodes for each type cluster
  let nodeId = 0;
  const typeNodes: Map<string, string> = new Map();

  for (const [type, typeScenarios] of byType) {
    const typeNodeId = `T${nodeId++}`;
    typeNodes.set(type, typeNodeId);
    mermaidLines.push(`${typeNodeId}["📋 ${type} Tests (${typeScenarios.length})"]`);
  }

  // Add scenario nodes
  const scenarioNodes: Map<string, string> = new Map();
  for (const scenario of scenarios) {
    const scenarioNodeId = `S${nodeId++}`;
    scenarioNodes.set(scenario.id, scenarioNodeId);

    const icon = scenario.priority === 'high' ? '🔴' : scenario.priority === 'medium' ? '🟡' : '🟢';
    const confidence = (scenario.confidence * 100).toFixed(0);

    mermaidLines.push(
      `${scenarioNodeId}["${icon} ${scenario.id}<br/>${scenario.title}<br/>(${confidence}%)"]`
    );

    // Connect to type
    const typeNodeId = typeNodes.get(scenario.testType);
    if (typeNodeId) {
      mermaidLines.push(`${typeNodeId} --> ${scenarioNodeId}`);
    }
  }

  const mermaidDiagram = mermaidLines.join('\n');

  // Save diagram
  const reportsDir = join(process.cwd(), '.test-kit', 'reports');
  mkdirSync(reportsDir, { recursive: true });

  const markdownContent = `# 🧩 Test Scenario Map

Generated at: ${new Date().toISOString()}

## Scenario Distribution

\`\`\`mermaid
${mermaidDiagram}
\`\`\`

## Statistics

- **Total Scenarios:** ${scenarios.length}
- **High Priority:** ${scenarios.filter((s) => s.priority === 'high').length}
- **Average Confidence:** ${(scenarios.reduce((sum, s) => sum + s.confidence, 0) / scenarios.length * 100).toFixed(1)}%

## By Type

${Array.from(byType.entries())
  .map(([type, scens]) => `- **${type}:** ${scens.length} scenarios`)
  .join('\n')}

## Test Implementation Guide

For each scenario above:
1. Create test file in \`__tests__/\`
2. Follow the test type guidelines (Unit/Integration/E2E)
3. Use the scenario steps as test structure
4. Add assertions for all related files
5. Update scenario status to "Complete"

---
*This map was auto-generated by Test-Kit AI Scenario Designer*
`;

  writeFileSync(join(reportsDir, 'scenario-map.md'), markdownContent);
  console.log('📊 Scenario tree rendered → .test-kit/reports/scenario-map.md');

  return markdownContent;
}
